import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.scss'
import {MantineProvider} from '@mantine/core';
import Navbar from "@/layout/Navbar/Navbar";
import Footer from "@/layout/Footer/Footer";
import {loadErrorMessages, loadDevMessages} from "@apollo/client/dev";
import {ApolloWrapper} from "@/lib/ApolloWrapper";
import {AuthProvider} from "@/context/AuthContext";
import AuthorizationCheck from "@/utils/AuthorizationCheck";

loadDevMessages();
loadErrorMessages();

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ApolloWrapper>
            <AuthProvider>
                <MantineProvider>
                    <AuthorizationCheck>
                        <Navbar/>
                        {children}
                        <Footer/>
                    </AuthorizationCheck>
                </MantineProvider>
            </AuthProvider>
        </ApolloWrapper>
        </body>
        </html>
    )
}
